all:
  children:
    cortensor_nodes:
      hosts:
        server1:
          ansible_host: 192.168.1.10
          key_pair_index: 1
          gpu_enabled: 0
        server2:
          ansible_host: 192.168.1.11
          key_pair_index: 2
          gpu_enabled: 0
        server3:
          ansible_host: 192.168.1.12
          key_pair_index: 3
          gpu_enabled: 0
        server4:
          ansible_host: 192.168.1.13
          key_pair_index: "4, 5, 6, 7" # Multiple keys can be used for the same server, quote is a must for multiple keys
          gpu_enabled: 0
          llm_threads: "4" # You can set threads per instance here, if not set, it will use (total threads count - 2) / total instances
        server5:
          ansible_host: 192.168.1.14
          key_pair_index: "11, 18" # Follow the numbering, not the index position
          gpu_enabled: 1 # set to 1 if GPU is available
          gpu_threshold: 10 # Set GPU threshold for LLM, if not set, it will use 0