networks:
  cnidsysmon: null
services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
    - ./config/loki-config.yaml:/etc/loki/config.yaml:ro
    - ./loki-data/boltdb:/var/lib/loki/index
    - ./loki-data/chunks:/var/lib/loki/chunks
    - ./loki-data:/var/lib/loki
    networks:
    - cnidsysmon
    ports:
    - 127.0.0.1:3100:3100
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
    - ./config/grafana-provisioning-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
    - ./config/grafana-provisioning-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    - ./grafana-data:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true" # Change to "false" if you want to disable no login access
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    networks:
    - cnidsysmon
    ports:
    - 127.0.0.1:3000:3000
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    entrypoint:
    - ''
    command:
    - sh
    - -c
    - mkdir -p /data/mimir && minio server --quiet /data
    environment:
    - MINIO_ROOT_USER=mimir
    - MINIO_ROOT_PASSWORD=supersecret
    volumes:
    - ./minio-data:/data
    networks:
    - cnidsysmon
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    command: '-config.file=/etc/mimir/config.yml -config.expand-env=true

      '
    volumes:
    - ./config/mimir-config.yml:/etc/mimir/config.yml:ro
    - ./mimir-data/data:/mimir-data
    networks:
    - cnidsysmon
    ports:
    - 127.0.0.1:9009:9009
    restart: unless-stopped
    depends_on:
      - minio
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - cnidsysmon
    ports:
    - 80:80
    depends_on:
    - grafana
    - loki
    - mimir
