apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  uid: mimir-prov
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  version: 1
  editable: false
  jsonData:
    httpHeaderName1: X-Scope-OrgID
  isDefault: true
- name: Loki
  type: loki
  uid: loki-prov
  access: proxy
  orgId: 1
  url: http://loki:3100
  version: 1
  editable: false
  jsonData:
    maxLines: 1000
    minInterval: 1s
    logLevelField: level
    logLevelValueMap:
      info: info
      warn: warn
      error: error
      debug: debug
