export const CORTENSOR_CONFIG = {
  ROUTER_URL: process.env.CORTENSOR_ROUTER_URL!,
  API_KEY: process.env.CORTENSOR_API_KEY!,
  COMPLETIONS_URL: process.env.NEXT_PUBLIC_CORTENSOR_COMPLETIONS_URL!,
  SESSION_ID: parseInt(process.env.NEXT_PUBLIC_DEEPSEEK_SESSION_ID!),
  TIMEOUT: parseInt(process.env.LLM_TIMEOUT!),
  MAX_TOKENS: parseInt(process.env.LLM_MAX_TOKENS!),
  MAX_INPUT_LENGTH: parseInt(process.env.NEXT_PUBLIC_MAX_INPUT_LENGTH!)
}

export const ORACLE_CONFIG = {
  MIN_CONSENSUS: parseInt(process.env.ORACLE_MIN_CONSENSUS || '3'),
  CONFIDENCE_THRESHOLD: parseFloat(process.env.ORACLE_CONFIDENCE_THRESHOLD || '0.8'),
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME || 'AI Oracle',
  APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION || 'v1.0'
}

export const WEB3_CONFIG = {
  SESSION_V2_ADDRESS: process.env.NEXT_PUBLIC_SESSION_V2_ADDRESS!,
  SESSION_QUEUE_V2_ADDRESS: process.env.NEXT_PUBLIC_SESSION_QUEUE_V2_ADDRESS!
}
